version: 2

# 设置操作系统和工具
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"  # 直接指定 Python 版本，不需要使用 asdf

  commands:
    # 安装项目依赖
    - pip install -r requirements.txt

    # 启动 Flask 应用
    - python main.py  # 或者使用适合你应用的启动命令
